# Generated by Django 5.1.2 on 2024-10-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_active',
            new_name='last_active_at',
        ),
    ]
